FROM python:3.12-slim

WORKDIR /app

COPY app/requirements.txt .

# Install dependencies using venv

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

CMD ["/bin/bash", "-c", "./migrate.sh"]

